site_name: cookingjournal
site_url: https://dwillmott.github.io/cookingjournal
theme:
  name: terminal
  features:
    - navigation.top.hide
    - navigation.side.toc.hide
  palette: gruvbox_dark
nav:
  - Log: index.md
  - Recipes: recipes.md
extra_css:
  - stylesheets/extra.css
