site_name: cookingjournal
site_url: https://dwillmott.github.io/cookingjournal
theme:
  name: terminal
    - navigation.top.hide
  palette: gruvbox_dark
nav:
  - Home: index.md
  - Recipes: recipes.md